@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
    "name": "Juan",
    "email": "juanpablo@gmail.com",
    "password": "123456"
}


###


# @name authenticate

POST {{baseUrl}}/sessions
Content-Type: application/json

{
    "email": "juanpablo@gmail.com",
    "password": "123456"
}

###

# @name review

POST {{baseUrl}}/reviews
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
   "establishmentId": "0x94dfb90392fe44d9:0xea16f3509e60fe5"
}

###

# @name create_establishment

POST {{baseUrl}}/establishment
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
   "url": "https://maps.app.goo.gl/nqsABVSeTCiHbJ327"
}

###

# @name list_all_establishment

GET {{baseUrl}}/establishment?id=0x9bd51fff4cc717:0x930f8a469526651c
Content-Type: application/json
Authorization: Bearer {{authToken}}
