@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}
# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
    "name": "Juan",
    "email": "juanpablo@gmail.com",
    "password": "123456"
}


###


# @name authenticate

POST {{baseUrl}}/sessions
Content-Type: application/json

{
    "email": "juanpablo@gmail.com",
    "password": "123456"
}

###

# @name review

POST {{baseUrl}}/reviews
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
   "establishmentId": "0x9bd5b81cec9b05:0xc9b595f28b3ca216"
}

###

# @name create_establishment

POST {{baseUrl}}/establishment
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
   "url": "https://maps.app.goo.gl/MQz1txFgBSa3nvBi9"
}

###

# @name list_all_establishment

GET {{baseUrl}}/establishment
Content-Type: application/json
Authorization: Bearer {{authToken}}
